### PR TITLE
day 24, 25 py

### PR DESCRIPTION
**Pull request by RongkunWang**
day 24.. 

also day 25:
using many help from https://www.reddit.com/r/adventofcode/comments/18qbsxs/2023_day_25_solutions/, wikipedia and google.

The maximum flow of the graph between two vertices from the two subgraphs is 3. So there are 3 paths beteween any two vertices of the two graph.
So I start to find the path between 0th vertex and another vertex V=1, using BFS, and remove all edges in each path. I did it 3 times to find the 3 flows. if there's only 3 flows, the two V are disconnected. This means they are in their own subgraph. Solution found. If more flows are find, they're on the same subgraph and just consider V+=1 until solution is found. Similar to https://www.reddit.com/r/adventofcode/comments/18qbsxs/comment/keue5sc/?utm_source=share&utm_medium=web2x&context=3 

This is a special case of Edmonds-Karp algorithm for solving maximum flow with capacity of 1 for each edge. The removal of edge in the above algorithm after one path found is the same as increasing the edge flow from 0 to 1 and thus preventing the next path to consider the same edge. 
I didn't implement the alg for finding the actual cuts, and many other people don't. All the edges removed are a superset of the three edges that actually need to be removed. And the extra edges doesn't affect the result, by creating more subgraphs. Why?

I think I'm just luky that the topology don't have some special scenario..

### CODE REVIEW

**Comment by RongkunWang** [comment]
@Moelf how to install numpy for our ci?

**Comment by Moelf** [comment]
I guess you can just run a pip in the CI, numpu is fast to install

**Comment by RongkunWang** [comment]
I constructed this input and indeed the result is not correct.
```
abc: edf ghi klm nop qrs tuv jjj mmm nnn                                                                                                                            
edf: ghi klm bbb
ghi: klm bbb
klm: bbb
jjj: mmm nnn bor
mmm: nnn bos
nnn: bot
nop: qrs tuv ccc
qrs: tuv ccc
tuv: ccc
bbb: bor bos bot
ccc: bor bos bot
bor: cor
bos: cos
bot: cot
cor: end enf
cos: end enf
cot: end enf
end: enf
```

So I improved the algorithm following exactly the golang, categorizing every single node. and it is now properly done.

**Comment by Moelf** [comment]
You can merge it whenever. Idk how you want to squash or not

**Pull request merged**
