### PR TITLE
day 21 22 py

### PR DESCRIPTION
**Pull request by RongkunWang**
Done with day 21. In theory can find the periodicity.

Day 22, double-linked list would be faster to loop instead of dependency matrix

### CODE REVIEW

**Comment by RongkunWang** [comment]
Tried using dictionary, it is faster in my computer. Also here on ci. @Moelf

**Comment by Moelf** [comment]
I'm sure it's faster I was just feeling dumb can't see a nice data structure and algorithm combo when I did it

**Comment by RongkunWang** [comment]
> I'm sure it's faster I was just feeling dumb can't see a nice data structure and algorithm combo when I did it

when I used the matrix I was even slower :D .

**Comment by Moelf** [comment]
My bricks are in a list but I don't encode the supporting relationship properly

**Pull request merged**
