### PR TITLE
day 23 py

### PR DESCRIPTION
**Pull request by RongkunWang**
First need to build up the proper graph. 

Then solve the problem of "longest path between two nodes in a graph". Unfortunately, Eric put plenty of cycles inside, and in part 2 it's guaranteed to be undirected, therefore there's no tricks. Although it seems Eric make the part 1 a directed graph, using the brute force approach is still very fast.

It took 30 second on my computer..

I plan to make a figure out of it(idea from Marco)

### CODE REVIEW

**Comment by RongkunWang** [comment]
all junction and their path.
[23.pdf](https://github.com/Moelf/AoC2023/files/13759762/23.pdf)

**Comment by RongkunWang** [comment]
Part 1
23_graph_part1

Part 2 To come

**Comment by Moelf** [comment]
beautiful

**Comment by RongkunWang** [comment]
I'm happy he didn't just allow greedy algorithm find the solution :D 
# Part 1
23_graph_part1
# Part 2
23_graph_part2

However python is still very slow!

**Comment by Moelf** [comment]
>However python is still very slow!

Use pypy?

**Comment by RongkunWang** [comment]
Baseline: 30-40 second
1. recursion to avoid copying of list. about 10 s improvement but subject to fluctuation
2. do not return the solution, to avoid copying. no significant changes
3. use set for visited(not able to track the path anymore). 7 second 😈 . Wow so the the time really is spent at "did I visit this before? 
4. map out nodes to indices for the grpah. avoid any unoptimal time complexity for add/find/remove for set. 4 second 😆 

btw, when you merge from your branch to main, does github ask you to merge main to my branch? Becuase I usually don't do the merge, I rebase, so that I can keep the history better sorted.

**Comment by Moelf** [comment]
Oh, I clicked update for this PR when I merged my so we can run on real inputs

**Pull request merged**
