### PR TITLE
Pay Julia JIT latency price once per day but so hacky

### PR DESCRIPTION
**Pull request by Moelf**
## Main
```
> time julia --startup-file=no --project=. runtests.jl julia

Test Summary:                                 | Pass  Total  Time
Day 04                                        |    8      8  2.8s
  julia   04_moelf.jl          04_example.txt |    2      2  0.7s
  julia   04_moelf.jl          04_moelf.txt   |    2      2  0.7s
  julia   04_moelf.jl          04_rk.txt      |    2      2  0.7s
  julia   04_moelf.jl          04_ylks.txt    |    2      2  0.7s
________________________________________________________
Executed in   14.67 secs    fish           external
   usr time   15.00 secs    0.00 micros   15.00 secs
   sys time    6.27 secs  986.00 micros    6.27 secs
```

## This PR
```
> time julia --startup-file=no runtests.jl julia
  Activating project at `~/Documents/github/AoC2023`

Test Summary:                                 | Pass  Total  Time
Day 04                                        |    8      8  0.2s
  julia   04_moelf.jl          04_example.txt |    2      2  0.2s
  julia   04_moelf.jl          04_moelf.txt   |    2      2  0.0s
  julia   04_moelf.jl          04_rk.txt      |    2      2  0.0s
  julia   04_moelf.jl          04_ylks.txt    |    2      2  0.0s

________________________________________________________
Executed in    2.56 secs    fish           external
   usr time    2.52 secs  763.00 micros    2.52 secs
   sys time    0.39 secs  136.00 micros    0.39 secs
```

### CODE REVIEW

**Comment by RongkunWang** [comment]
Don't over-do AOC lol..

**Comment by RongkunWang** [comment]
> Don't over-do AOC lol..
You could use stages of the ci, compile in first stage and pass the artifacts for the second stage for tests.

If the ci time is too long you can spawn different days into different jobs, or one job per input. But I'm not sure if ci could read from directory dynamically and spawn jobs, so maybe you'd have to manually change workflow every day? You could also spawn 25 jobs and in each job detects if inputs are there, if not, pass as succeeful.

**Comment by Moelf** [comment]
I think the cleanest way is to ask Julia submitters (i.e. me) to write every day in:

```julia
module DayN
...
end
```

but this PR seems to work albeit hacky, and it allows everyday's script to stay in individually-runnable script

**Comment by Moelf** [comment]
But for JIT based language, running is compiling..

**Pull request merged**
