### PR TITLE
add day 15 py

### PR DESCRIPTION
**Pull request by RongkunWang**
Literally just do as the description.

### CODE REVIEW

**Comment by Moelf** [comment]
how did you find time???

**Comment by RongkunWang** [comment]
I was supposed to meet someone very soon so I couldn't resist opening the page. 

We need to study how much productivity AoC has dragged.

**Comment by Moelf** [comment]
>We need to study how much productivity AoC has dragged.

some people view certain games as productivity booster, for example Shopify allows their employee to expense the game Factorio (https://nitter.net/tobi/status/1493007949119340555#m)

Maybe AoC is similar -- it's training for better productivity in the long run

**Comment by RongkunWang** [comment]
oh fun a new game for me to pay attention. I do like games, some games feel like work, or work simulators :D

I wonder if they mean playing it in work time though

**Comment by Moelf** [comment]
Oh boi, Factorio is like real work but compressed so it's addictive: you're more productive in it than real life 😂

**Pull request merged**
